# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Docs Deploy

on:
  push:
    tags:
      - v*
    branches:
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: npm install
      - name: Run CI Build
        run: npm run ci
  # test-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v2
  # test-mac:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
